### PR TITLE
added negative precision, round half to zero, round 9.999, %n formatting test cases

### PR DESCRIPTION
**Pull request by michaelgiraldo**
After passing 3900+ test and still failing Moulinette. I am adding additional test cases:
- Negative precision for specifiers diouxXfegpcs
- round half to even for specifiers feg
- round 9.0, 9.9, 9.99, 0.099, 0.99 which are test cases for specifiers feg

### CODE REVIEW

**Comment by gavinfielder** [comment]
You know what, keep all the rounding tests. Testing rounding at low precision wasn't covered, so they all seem relevant now.

Rounding tests currently use `rnd` in the name, so `bonus_f_rnd_` would be consistent with the current naming conventions.

**Comment by michaelgiraldo** [comment]
- rename the functions as per the test naming conventions
- reduced the number of test case as per feedback
- remove %i %c negative precision tests as per feedback
- however, left two test cases (null) for %s negative precision to insure completeness, as those are tested in cclaude42/PFT_2019 new2019_negstar_4 & new2019_negstar_5 test cases

**Comment by michaelgiraldo** [comment]
Added %n formatting test cases, which found several issues with my ft_printf. The test focus on the proper formatting %n.

**Comment by michaelgiraldo** [comment]
Had to perform **./reset-to-default-enabled-tests**  on a macOS as it was not working on Linux. Check if tests have been disabled.

**Pull request merged**
